# Russ Savela
# CS-499
# 
# Jekyll configuration file
#

remote_theme: jekyll-theme-architect
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Russ Savela's CS-499 Portfolio
description: A portfolio site showcasing my work in CS-499.